### ISSUE TITLE
Truncation isn't UTF-8 compatible

### ISSUE THREAD

**Issue by kirkstrobeck** [symphonists/search_index#28]
```
<excerpt><p> img_0335_2-4ea5b0c3834e0.jpg 1163 2011-10-24 Schminkanleitung: Step 1: Zeichnen Sie mit dem Kinder-Schminkstift Grün eine ovale Form über das ganze Gesicht. Anschließend mischen Sie aus den Tiegel-Farben Grün, Gelb und Weiß ein blasses gelb-gr�&#8230;</p></excerpt>
```

Having issues with German characters being broken into non characters,  
my guess is a UTF-8 substring error somewhere ..

_Taken from .._

```
Zeichnen Sie mit dem Kinder-Schminkstift Grün eine ovale Form über das ganze Gesicht. Anschließend mischen Sie aus den Tiegel-Farben Grün, Gelb und Weiß ein blasses gelb-grün zusammen und malen damit die Fläche mit dem breiten Pinsel aus.
```

I checked thru the code and saw your `mb_substring` fix anf the call to `self`, so I'm stumped :(

The XSLT error page displays

```
loadXML(): Input is not proper UTF-8, indicate encoding ! Bytes: 0xC3 0x26 0x23 0x38 in Entity, line: 760
```

**Comment by nitriques** [comment]
@animaux Would this be useful ? We have a method in the General class that handles mb_string when installed.

**Comment by animaux** [comment]
I haven’t encountered this myself but it would be useful to since it should not only affect german chars but plenty other UTF characters. (I think.)

**Comment by michael-e** [comment]
I remember that the UTF-8 truncation issue has been fixed in the Symphony core some time ago. (Probably it uses the method from the General class which @nitriques mentioned.)

**Comment by animaux** [comment]
@michael-e So this is likely fixed then?

**Comment by michael-e** [comment]
Yes, it is fixed in the core, as far as I know. One might take a look there to see how it has been done. :-)

**Comment by animaux** [comment]
That would likely be pearls before swine in my case `:D`.

**Comment by michael-e** [comment]
So you can only hope for @nitriques getting his hands dirty while you sit back and relax. :-)

**Comment by animaux** [comment]
Better than the ol’ carpenter *fixing* the delicate watch clockwork, I guess.

**Comment by nitriques** [comment]
Great to see this! Closing!
