### ISSUE TITLE
2.6 Compatibility/Issues

### ISSUE THREAD

**Issue by animaux** [symphonists/search_index#52]
After updating to 2.6: New entries are not indexed and I cannot select a section to reindex.

Are [these fixes](https://github.com/symphonists/elasticsearch/commit/a57e510f6893c369074beb2d37de722966ce7fd5) possibly applicable to search index too?

**Comment by brendo** [comment]
> Are these fixes possibly applicable to search index too?

With regards to the second part of the bug, most probably. The `selectable` class will be missing from the table.

I can't answer for the first part though.

**Comment by moretaste** [comment]
Have a similar issue on a 2.5.2 install. Doesn't have test it thoroughly but it seems 
* if you make an index for the  first time it works. 
* After the first reindex the back-end shows a count 
* if you refresh the searchindex page the count is 0 and the database entry is empty

**Comment by animaux** [comment]
Thanks @brendo, Making the index selectable again using the elasticsearch code did work!

So, part of the problem are:

`…/extensions/search_index/lib/class.entry_xml_datasource.php` line 30 and
`…/extensions/search_index/lib/class.entry_xml_datasource.php` line 36

pointing to the no more existent file `…/extensions/search_index/lib/class.reindex_datasource.php`

I have tried to make these lines pointing to `class.datasource.section.php` instead, but apparently this does not solve the problem. I can start a reindex now but it leads to a server error 500.

@brendo any chance you might have a look at this? Search index is a very vital extension for some of my sites and apparently the only major thing left (for me) broken in 2.6.x.

**Comment by animaux** [comment]
Unfortunately the server error is not logged into the error_log :(

**Comment by brendo** [comment]
Which version of Search Index are you running? It looks like some of these changes already exist in the codebase:

- [selectable](https://github.com/symphonists/search_index/blob/master/content/content.indexes.php#L353-L360)
- [references to `SectionDatasource`](https://github.com/symphonists/search_index/blob/master/lib/class.entry_xml_datasource.php#L5)

**Comment by animaux** [comment]
m( D’oh … switching to `0.9.3` from the integration branch solved the issues. Sorry for bothering!

**Comment by moretaste** [comment]
same error still exists for me on a 2.5.2 both with the master and integration branch.

First time re-index gives and stores entries, second time a re-index and there are 0 entries. I will update this week to 2.6 to see if the error still occurs.

**Comment by moretaste** [comment]
Seems to work with 2.6.x
