### ISSUE TITLE
Missing latest release?

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/search_index#53]
As reported in https://github.com/symphonists/search_index/issues/52 concerning the Symphony 2.6.x compatibility, which should solve the `0.9.3` tag release, the current master has a `0.9.3` release entry in its `extension.meta.xml`, but it does not work like said in #52, and the latest github tag to be found is `0.9.1`.

Did the latest updates gone missing somehow?

**Comment by nitriques** [comment]
Is the integration branch working ? did you test it ?

I do not use this extensions, but I would be glad to release it if you confirm it's working.

**Comment by nitriques** [comment]
Seems like only the readme has been touched... https://github.com/symphonists/search_index/compare/integration

**Comment by jurajkapsz** [comment]
Yes, I've tested also integration, they are almost the same as you write. Anyway, both do not work.

I get an error in main log (and similar on js console) `Fatal Error: Javascript - Uncaught TypeError: Cannot read property 're-index-refresh-rate' of null in file .../extensions/search_index/assets/search_index.js on line 24` when I visit the `Search Index` > `Indexes` page.

**Comment by nitriques** [comment]
Hum.... any solutions ?

**Comment by brendo** [comment]
Check your `config.php` file, do you have a property in the Search Index section called `re-index-refresh-rate`?

**Comment by jurajkapsz** [comment]
> Check your config.php file, do you have a property in the Search Index section called re-index-refresh-rate?

OMG. The whole `SEARCH_INDEX` section was missing there, but my fault. I left my `manifest` folder read-only from this https://github.com/symphonycms/symphony-2/issues/2439 testing and I did not get any warnings when the Search Index extension could not write into the `config.php`.

Gee, sorry.

So, the extension is working.

**Comment by brendo** [comment]
No worries.

I've also pushed the 0.9.3 as the release stood when @nathanhornby intended it to be. I've done a new 'release', 0.9.4 for the current `master` as well.

**Comment by jurajkapsz** [comment]
Thanks Brendo & Nicolas!

**Comment by nitriques** [comment]
Thanks Brendan!
