### ISSUE TITLE
Datasource returns no results on 2.6.5 and 2.6.4 

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/search_index#54]
I have an installation with Symphony 2.6.4 and 2.6.5 and my datasource doesn't contain my field searchindex, the field searchindex is added, but in debugging doesn't appear. I use 0.9.4 version of the Search_Index.
I have index 10 items.. have it running on other sites (2.6.4) works perfect.

Uninstalled the extension, readded the field, reindex, readded to the datasource, but nothing.

I have noticed 1 difference in my config.php compared to other working sites:
no single quotes for the numbers
're-index-per-page' => 20,
So i have added them, but no difference.

Where should i start to debug?

	###### SEARCH_INDEX ######
		'search_index' => array(
			're-index-per-page' => '20',
			're-index-refresh-rate' => '0.5',
			'get-param-prefix' => null,
			'get-param-keywords' => 'keywords',
			'get-param-per-page' => 'per-page',
			'get-param-sort' => 'sort',
			'get-param-direction' => 'direction',
			'get-param-sections' => 'sections',
			'get-param-page' => 'page',
			'default-sections' => null,
			'default-per-page' => '20',
			'default-sort' => 'score',
			'default-direction' => 'desc',
			'excerpt-length' => '250',
			'min-word-length' => '3',
			'max-word-length' => '30',
			'stem-words' => 'yes',
			'build-entries' => 'no',
			'mode' => 'like',
			'log-keywords' => 'yes',
			'indexes' => 'a:1:{i:60;a:3:{s:6:"fields";a:1:{i:0;s:3:"sku";}s:9:"weighting";s:1:"0";s:7:"filters";a:0:{}}}'
		),

**Comment by nitriques** [comment]
I would start here: https://github.com/symphonists/search_index/blob/master/data-sources/data.search.php#L53

And then var_dump things on the way down...

**Comment by wdebusschere** [comment]
Nitriques,

I use the Search Index field  not the search datasource.

Thx

**Comment by wdebusschere** [comment]
Ok, problem solved:
I tought the re-index entries would automatically fill the search index field of my section, but this is not it's function, when i edit an entry or create an entry the information is available in my datasource.

**Comment by nitriques** [comment]
Oh, great then!

**Comment by kamwing** [comment]
Datasource returns no results on 2.6.7
