### ISSUE TITLE
preg_replace /e flag neccessary?

### ISSUE THREAD

**Issue by animaux** [symphonists/search_index#56]
Is the deprecated preg_replace `/e` flag neccessary in [this line](https://github.com/symphonists/search_index/blob/master/lib/class.search_index.php#L319)?

I have not got an error yet, but I’m not sure when exactly this is line run. I wonder if the `/e` flag is needed here, since there is no retrieved stored value in the replacement.

**Comment by nitriques** [comment]
Yes it is, it to call str_replace

`str_replace(' ', 'SEARCH_INDEX_SPACE', '$0')`

I do not know out to get the $0 value in the callback...

**Comment by nitriques** [comment]
Looks like it would be 

```php
return str_replace(' ', 'SEARCH_INDEX_SPACE', $m[0]);
```
?

**Comment by animaux** [comment]
Hmm, thanks. I really would like to get an error before fixing this. Will try to find out when this is triggered.

**Comment by animaux** [comment]
The `manipulateKeywords()`-function that contains the questionable code is not referenced anywhere else in the extension, so would it be safe to say it’s not used? Probably some leftover? Or could it be invoked in any other way?

I’ve commented out the whole function declared [here](https://github.com/symphonists/search_index/blob/master/lib/class.search_index.php#L316). I have yet to encounter an error. All seems to work well.

**Comment by nitriques** [comment]
@animaux You're right. Wanna send a PR with this deletion please ?

**Comment by nitriques** [comment]
I'll leave this open until it's fixed in master ;)

**Comment by nitriques** [comment]
Fixed in #55
